/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cenfotec.componentes.control;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Fabia
 */
public class PanelMastermind extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelMastermind() {
        initComponents();
        this.jTextField1.setEnabled(false);
        this.jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("Comenzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Comparar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Aciertos Parciales: ");

        jLabel2.setText("Intentos Restantes: ");

        jLabel4.setText("0");

        jLabel5.setText("0");

        jLabel3.setText("Aciertos Totales: ");

        jLabel6.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(38, 38, 38))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Se establecen los valores predeterminados
        if (!comenzarJuego) {
            comenzarJuego = true;
            contParcial = 0;
            contTotal = 0;
            intentos = 8;
            palabraAdivinar = "";
            this.jTextField1.setText("");
            this.jTextField1.setEnabled(true);
            this.jButton2.setEnabled(true);

            this.jLabel5.setText(Integer.toString(contParcial));
            this.jLabel4.setText(Integer.toString(contTotal));
            this.jLabel6.setText(Integer.toString(intentos));

            //Se crea la palabra aleatoriamente
            for (int i = 0; i < 4; i++) {
                palabraAdivinar += colores[(int) (Math.random() * (colores.length - 1) + 1)];
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //Se establecen la cantidad de intentos restantes
        intentos--;
        this.jLabel6.setText(Integer.toString(intentos));

        //Si el juego ha comenzado y el jugador tiene más de 1 intento,
        //el juego continúa
        if (comenzarJuego && intentos > 0) {
            String palabraNueva = this.jTextField1.getText();
            palabraNueva = palabraNueva.toUpperCase();

            //La palabra ingresada se convierte en char para la manipulación de las letras
            char[] result = palabraNueva.toCharArray();

            //Si la palabra ingresada corresponde a la palabra a adividar, entonces gana el juego siempre y cuando
            //No haya agotado sus intentos
            if (palabraNueva.equals(palabraAdivinar)) {
                comenzarJuego = false;
                this.jTextField1.setEnabled(false);
                this.jButton2.setEnabled(false);
                System.out.println("Partida ganada");
                this.jLabel5.setText(Integer.toString(0));
                this.jLabel4.setText(Integer.toString(palabraAdivinar.length()));
                showMessageDialog(null, "Felicidades, ha ganado la partida!");
            } else {

                //Se validan cuántos son los aciertos totales
                for (int i = 0; i < palabraNueva.length(); i++) {
                    if (result[i] == palabraAdivinar.charAt(i)) {
                        contTotal++;
                        //Si coincide alguno, entonces se ocula el caracter respectivo
                        result[i] = '-';
                    }
                }
                //Se validan cuántos son los aciertos parciales
                if (contTotal < 4) {
                    for (int i = 0; i < result.length; i++) {
                        for (int j = 0; j < palabraAdivinar.length(); j++) {
                            if (result[i] == palabraAdivinar.charAt(j)) {
                                if (i != j) {
                                    contParcial++;
                                }
                                break;
                            }
                        }
                    }
                }

            }
            
            //Se imprimen los resultados y luego de restablecen para el próximo intento
            this.jLabel5.setText(Integer.toString(contParcial));
            this.jLabel4.setText(Integer.toString(contTotal));

            contParcial = 0;
            contTotal = 0;

        } else {
            //Se le muestra al jugador si ha perdido la partida
            System.out.println("Partida perdida");
            this.jTextField1.setEnabled(false);
            this.jButton2.setEnabled(false);
            comenzarJuego = false;
            showMessageDialog(null, "Partida perdida -> " + palabraAdivinar);

        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    //Inicializo las variables del juego
    private boolean comenzarJuego = false;
    private String palabraAdivinar = "";
    private int contTotal = 0;
    private int contParcial = 0;
    private int intentos = 0;

    //Arreglo de colores
    //Azul(A) - Rojo(R) - Blanco(B) - Negro(N) - Verde(V) - Amarillo(M)
    String[] colores = new String[]{"A", "R", "B", "N", "V", "M"};

}
